# Generated by Django 3.1.1 on 2020-09-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20200915_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(choices=[('HB', 'Hobbit'), ('LOTR', 'Lord Of The Rings')], max_length=36, null=True, unique=True),
        ),
    ]
